### PR TITLE
feat: Use Chromium instead of Firefox

### PR DESCRIPTION
**Pull request by maricn**
## Why
Login page is blank and this tool doesn't work on my machine (Arch Linux, geckodriver 0.29.1). I found `selenium_stealth` package which fixes the problem, but it is only supporting Chrome driver.

## Changes in PR
* fix: Blank login page on ebay-k due to selenium detection. Use selenium_stealth.
* chore: Update README.md to simplify usage, remove instructions for manual geckodriver download and installation.
* chore: Remove unused `sandbox.py`

## Notes
Feel free to close this PR, I just fixed the bug and cleaned it up for myself, so if you want take it or leave it. Cheers and thanks for the prior work!

### CODE REVIEW

**Comment by pesimon** [comment]
Works like a charm - thx. 

On MacOS I needed to
* `brew install chromedriver`
* Set options to use chromium 
 ```
    options = webdriver.ChromeOptions()
    options.binary_location = "/Applications/Chromium.app/Contents/MacOS/Chromium"
 ```
* Install a specific version of chromium, chromedriver was asking for e.g. from
https://chromium.cypress.io/mac/

**Comment by maricn** [comment]
@pesimon I don't have a OSX machine atm, but would you say omitting `binary_location` parameter is possible if `Chromium` executable is on the `$PATH` envvar?

Then I could update the instructions to add:
1. download chromium from the link you provided and 
2. add the executable to the `PATH`

Is installing `chromedriver` necessary on OSX even if you install Chromium first? I have `chromium` AUR package installed, it brings `chromedriver` with itself...

**Comment by donwayo** [comment]
Hi @maricn, I would like to test this on Windows before merging. Thanks a lot for the contribution!

**Comment by Tschak77** [comment]
Hi @donwayo, it works good with Windows in my case.

I add also here encoding="utf-8" because of äöüß for German.

```
    if ad.get("description_file", None) is not None:
        description_file = ad.get("description_file")
        with open(description_file, "r", encoding="utf-8") as f:
            description_lines = f.readlines()
```

and changed here because I don't like the double newline

```
    for p in description_lines:
        text_area.send_keys(p)
#        text_area.send_keys(Keys.RETURN)
```

**Comment by donwayo** [comment]
Thanks all!

**Comment by neon-dev** [comment]
The "Prerequisites" and "Windows" sections still list the geckodriver dependency, which is not needed anymore (?)
Also, what do we need exactly as a subsitute on Windows? I don't have Chrome or Chromium installed and tried to provide the chromedriver manually but without success.

**Comment by Tschak77** [comment]
I just have 

- installed chrome
- python3 installed selenium_stealth
- download https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_win32.zip and unzip in ebaykleinanzeigen folder

and is was running well

**Comment by Tschak77** [comment]
my recommendation is working with PowerShell because ist automatically on every Windows 10

1. install chrome
2. install Python3 from the Windows Store
2. Run  python3 -m pip install selenium_stealth (to install selenium_stealth)
3. download https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_win32.zip and unzip in ebayKleinanzeigen folder
4. modification on kleinanzeigen.py
    line 267 add econding="utf-8" `with open(description_file, "r", encoding="utf-8") as f:`
    line 279 delete line `text_area.send_keys(Keys.RETURN)` because I don't like double new lines
5. add your deals to config.json update the rest of settings
5. In PowerShell change to ebayKleinanzeigen folder and run python3 kleinanzeigen.py --profile config.json

sorry I'm not a professional programmer but that helped me.

**Comment by neon-dev** [comment]
Ok so installing Chrome is a requirement now. Without Chrome it gives this error:
> selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

That's a huge dependency compared to the geckodriver before, just to get around the selenium detection :(

Anyway, README.md definitely isn't fully up to date right now.
@Tschak77 maybe you can create a PR with this and the modifications you mentioned? You can edit files directly on Github if that's easier for you.

**Comment by Tschak77** [comment]
Hi @neon-dev, do I understand right, first I have to create a fork and then a PR?

**Comment by maricn** [comment]
enabling "Issues" on this repo would help keep track of things, imho..

and i was waiting on feedback from @pesimon on OSX stuff to merge this PR..

but i'm happy that someone else takes over Windows stuff as I don't have access to testing it on Windows..

**Comment by Tschak77** [comment]
@neon-dev done I hope it is correct. It has to be tested on another pc

**Comment by neon-dev** [comment]
Tested it and in general it works 👍
But I found a number of unclear, incomplete, missing or wrong ordered steps over the whole README.md (Linux, macOS and Windows). They will be fixed with #22 once [my changes](https://github.com/Tschak77/ebayKleinanzeigen/pull/1) are accepted.

**Pull request merged**
